model:
  type: phobert_vit
  vit_model: google/vit-base-patch16-224-in21k
  phobert_model: vinai/phobert-base
  hidden_dim: 256
  dropout: 0.3

data:
  # train_annotation: data/annotations/train.json
  # val_annotation:   data/annotations/val.json
  # test_annotation:  data/annotations/test.json
  train_annotation: data/annotations/train_segmented.json
  val_annotation:   data/annotations/val_segmented.json
  test_annotation:  data/annotations/test_segmented.json
  image_dir:        data/images/processed
  answer2idx_path:  data/annotations/answer2idx.json
  max_question_length: 20

training:
  batch_size:     8
  num_epochs:     10
  learning_rate:  0.00002
  save_dir:       checkpoints/
  log_dir:        logs/
  device:         cuda
  num_workers:    2
  prefetch_factor: 4
  save_every_step: 500
  resume: true
  resume_from: step_30.pt